### ISSUE TITLE
deze tutorial heeft jullie code gestolen

### ISSUE THREAD

**Issue by vdkuipb** [stepperman/asstroids#1]
Je hebt feedback gekregen van **Burritosss**
op:
```c
}
    [SerializeField] private float maxdistance = 2 
```

URL: https://github.com/stepperman/asstroids/blob/master/asstroids/Assets/Scripts/Water.cs

Feedback: https://gamedevelopment.tutsplus.com/tutorials/creating-dynamic-2d-water-effects-in-unity--gamedev-14143[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"2b45328aa2f4ce78e66f7299b81f8b6ef5cd4dbe","path":"asstroids/Assets/Scripts/Water.cs","reviewer":"Burritosss"}')

**Comment by gwnvisje** [comment]
Yep, dankjewel. En hoe is m'n andere gestolen code dan?
