### ISSUE TITLE
deze youtuber heeft ook jullie code gestolen

### ISSUE THREAD

**Issue by vdkuipb** [stepperman/asstroids#2]
Je hebt feedback gekregen van **Burritosss**
URL: https://github.com/stepperman/asstroids/blob/master/asstroids/Assets/Scripts/Player/PlayerMovement.cs

Feedback: https://www.youtube.com/watch?v=MbWK8bCAU2w&list=PLFt_AvWsXl0f0hqURlhyIoAabKPgRsqjz[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"140adac552f54bba3e485cce2be599e2b4a9ad2b","path":"asstroids/Assets/Scripts/Player/PlayerMovement.cs","reviewer":"Burritosss"}')

**Comment by gwnvisje** [comment]
Verkeerde, die heb ik zelf gemaakt.

https://github.com/stepperman/asstroids/blob/master/asstroids/Assets/Scripts/Player/PlatformerCollision.cs

Hier is de goede link waar ik dat vandaan heb. Ik heb het wel van het internet, ik wist niet dat er een video van was. Dit is de slechtste code review die ik heb meegemaakt, je hoeft niet zo eigenwijs te doen, en review de andere code eens.
